# CUDA_VISIBLE_DEVICES=1 python3 train_at.py --name ViT_PSPNet_CITY_all --data_dir ../pytorch-segmentation/pro_data/PSPNet_CITY/ --model_data_type PSPNet_CITY --gradient_accumulation_steps 4 --model_type ViT-B_16 --pretrained_dir ../ViT_ckpts/ViT-B_16.npz --loss_range all --train_batch_size 16 --eval_batch_size 16 --data_name feature_box_level_ViT --input_feature_dim 23 --num_steps 20000 --eval_every 5000 --warmup_steps 2000 --learning_rate 0.03 --enable_backbone_grad --max_grad_norm 10 --ordinal_class_num 50 --region_size 16 --enable_wandb

# CUDA_VISIBLE_DEVICES=1 python3 train_at.py --name ViT_UNet_CITY_all --data_dir ../pytorch-segmentation/pro_data/UNet_CITY/ --model_data_type UNet_CITY --gradient_accumulation_steps 4 --model_type ViT-B_16 --pretrained_dir ../ViT_ckpts/ViT-B_16.npz --loss_range all --train_batch_size 16 --eval_batch_size 16  --data_name feature_box_level_ViT --input_feature_dim 23 --num_steps 20000 --eval_every 5000 --warmup_steps 2000 --learning_rate 0.03 --enable_backbone_grad --max_grad_norm 10 --ordinal_class_num 50 --region_size 16 --enable_wandb

# CUDA_VISIBLE_DEVICES=1 python3 train_at.py --name ViT_SEGNet_CITY_all --data_dir ../pytorch-segmentation/pro_data/SEGNet_CITY/ --model_data_type SEGNet_CITY --gradient_accumulation_steps 4 --model_type ViT-B_16 --pretrained_dir ../ViT_ckpts/ViT-B_16.npz --loss_range all --train_batch_size 16 --eval_batch_size 16 --data_name feature_box_level_ViT --input_feature_dim 23 --num_steps 20000 --eval_every 5000 --warmup_steps 2000 --learning_rate 0.03 --enable_backbone_grad --max_grad_norm 10 --ordinal_class_num 50 --region_size 16 --enable_wandb

# CUDA_VISIBLE_DEVICES=1 python3 train_at.py --name ViT_DeepLab_CITY_all --data_dir ../pytorch-segmentation/pro_data/DeepLab_CITY/ --model_data_type DeepLab_CITY --gradient_accumulation_steps 4 --model_type ViT-B_16 --pretrained_dir ../ViT_ckpts/ViT-B_16.npz --loss_range all --train_batch_size 16 --eval_batch_size 16  --data_name feature_box_level_ViT --input_feature_dim 23 --num_steps 20000 --eval_every 5000 --warmup_steps 2000 --learning_rate 0.03 --enable_backbone_grad --max_grad_norm 10 --ordinal_class_num 50 --region_size 16 --enable_wandb

# CUDA_VISIBLE_DEVICES=1 python3 train_at.py --name ViT_FCN_CITY_all --data_dir ../pytorch-segmentation/pro_data/FCN_CITY/ --model_data_type FCN_CITY --gradient_accumulation_steps 4 --model_type ViT-B_16 --pretrained_dir ../ViT_ckpts/ViT-B_16.npz --loss_range all --train_batch_size 16 --eval_batch_size 16 --data_name feature_box_level_ViT --input_feature_dim 23 --num_steps 20000 --eval_every 5000 --warmup_steps 2000 --learning_rate 0.03 --enable_backbone_grad --max_grad_norm 10 --ordinal_class_num 50 --region_size 16 --enable_wandb

# CUDA_VISIBLE_DEVICES=1 python3 train_at.py --name ViT_PSPNet_VOC_all --data_dir ../pytorch-segmentation/pro_data/PSPNet_VOC/ --model_data_type PSPNet_VOC --gradient_accumulation_steps 4 --model_type ViT-B_16 --pretrained_dir ../ViT_ckpts/ViT-B_16.npz --loss_range all --train_batch_size 16 --eval_batch_size 16 --data_name feature_box_level_ViT --input_feature_dim 25 --num_steps 20000 --eval_every 5000 --warmup_steps 2000 --learning_rate 0.03 --enable_backbone_grad --max_grad_norm 10 --ordinal_class_num 50 --region_size 16 --enable_wandb

# CUDA_VISIBLE_DEVICES=1 python3 train_at.py --name ViT_DeepLab_VOC_all --data_dir ../pytorch-segmentation/pro_data/DeepLab_VOC/ --model_data_type DeepLab_VOC --gradient_accumulation_steps 4 --model_type ViT-B_16 --pretrained_dir ../ViT_ckpts/ViT-B_16.npz --loss_range all --train_batch_size 16 --eval_batch_size 16 --data_name feature_box_level_ViT --input_feature_dim 25 --num_steps 20000 --eval_every 5000 --warmup_steps 2000 --learning_rate 0.03 --enable_backbone_grad --max_grad_norm 10 --ordinal_class_num 50 --region_size 16 --enable_wandb

# CUDA_VISIBLE_DEVICES=1 python3 train_at.py --name ViT_FCN_VOC_all --data_dir ../pytorch-segmentation/pro_data/FCN_VOC/ --model_data_type FCN_VOC --gradient_accumulation_steps 4 --model_type ViT-B_16 --pretrained_dir ../ViT_ckpts/ViT-B_16.npz --loss_range all --train_batch_size 16 --eval_batch_size 16 --data_name feature_box_level_ViT --input_feature_dim 25 --num_steps 20000 --eval_every 5000 --warmup_steps 2000 --learning_rate 0.03 --enable_backbone_grad --max_grad_norm 10 --ordinal_class_num 50 --region_size 16 --enable_wandb

# CUDA_VISIBLE_DEVICES=1 python3 train_at.py --name ViT_SEGNet_VOC_all --data_dir ../pytorch-segmentation/pro_data/SEGNet_VOC/ --model_data_type SEGNet_VOC --gradient_accumulation_steps 4 --model_type ViT-B_16 --pretrained_dir ../ViT_ckpts/ViT-B_16.npz --loss_range all --train_batch_size 16 --eval_batch_size 16 --data_name feature_box_level_ViT --input_feature_dim 25 --num_steps 20000 --eval_every 5000 --warmup_steps 2000 --learning_rate 0.03 --enable_backbone_grad --max_grad_norm 10 --ordinal_class_num 50 --region_size 16 --enable_wandb

CUDA_VISIBLE_DEVICES=1 python3 train_at.py --name ViT_UNet_COCO_all --data_dir ../pytorch-segmentation/pro_data/UNet_COCO/ --model_data_type UNet_COCO --gradient_accumulation_steps 4 --model_type ViT-B_16 --pretrained_dir ../ViT_ckpts/ViT-B_16.npz --loss_range all --train_batch_size 16 --eval_batch_size 16 --data_name feature_box_level_ViT --input_feature_dim 186 --num_steps 20000 --eval_every 5000 --warmup_steps 2000 --learning_rate 0.03 --enable_backbone_grad --max_grad_norm 10 --ordinal_class_num 50 --region_size 16 --enable_wandb